# Generated by Django 5.2.1 on 2025-05-09 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=50, unique=True, verbose_name='Hava Aracı Modeli')),
            ],
            options={
                'verbose_name': 'Hava Aracı Modeli',
                'verbose_name_plural': 'Hava Aracı Modelleri',
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WING', 'Kanat'), ('FUSELAGE', 'Gövde'), ('TAIL', 'Kuyruk'), ('AVIONICS', 'Aviyonik')], max_length=50, unique=True, verbose_name='Parça Tipi')),
            ],
            options={
                'verbose_name': 'Parça Tipi',
                'verbose_name_plural': 'Parça Tipleri',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Takım Adı')),
                ('team_type', models.CharField(choices=[('WING_TEAM', 'Kanat Takımı'), ('FUSELAGE_TEAM', 'Gövde Takımı'), ('TAIL_TEAM', 'Kuyruk Takımı'), ('AVIONICS_TEAM', 'Aviyonik Takımı'), ('ASSEMBLY_TEAM', 'Montaj Takımı')], max_length=50, verbose_name='Takım Tipi')),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Seri Numarası')),
                ('production_date', models.DateTimeField(auto_now_add=True, verbose_name='Üretim Tarihi')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Kullanıma Hazır'), ('USED', 'Kullanıldı'), ('RECYCLED', 'Geri Dönüştürüldü')], default='AVAILABLE', max_length=20, verbose_name='Parça Durumu')),
                ('aircraft_model_compatibility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircraft_production_app.aircraftmodel', verbose_name='Uyumlu Araç')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircraft_production_app.parttype', verbose_name='Parça Tipi')),
                ('produced_by_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produced_parts', to='aircraft_production_app.team', verbose_name='Üreten Takım')),
            ],
            options={
                'verbose_name': 'Üretilmiş Parça',
                'verbose_name_plural': 'Üretilmiş Parçalar',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='aircraft_production_app.team', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ASSIGNED', 'Atandı'), ('IN_PROGRESS', 'Üretimde'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='PENDING', editable=False, max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('target_completion_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tamamlanma Tarihi')),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircraft_production_app.aircraftmodel', verbose_name='Üretilecek Hava Aracı Modeli')),
                ('assigned_to_assembly_team', models.ForeignKey(blank=True, limit_choices_to={'team_type': 'ASSEMBLY_TEAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='aircraft_production_app.team', verbose_name='Atanan Montaj Takımı')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Yönetici')),
            ],
            options={
                'verbose_name': 'İş Emri',
                'verbose_name_plural': 'İş Emirleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Hava Aracı Seri Numarası')),
                ('assembly_date', models.DateTimeField(auto_now_add=True, verbose_name='Montaj Tarihi')),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircraft_production_app.aircraftmodel', verbose_name='Hava Aracı Modeli')),
                ('avionics', models.OneToOneField(limit_choices_to={'part_type__category': 'AVIONICS'}, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_as_avionics', to='aircraft_production_app.part', verbose_name='Aviyonik Sistem (Parça SN)')),
                ('fuselage', models.OneToOneField(limit_choices_to={'part_type__category': 'FUSELAGE'}, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_as_fuselage', to='aircraft_production_app.part', verbose_name='Gövde (Parça SN)')),
                ('tail', models.OneToOneField(limit_choices_to={'part_type__category': 'TAIL'}, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_as_tail', to='aircraft_production_app.part', verbose_name='Kuyruk (Parça SN)')),
                ('wing', models.OneToOneField(limit_choices_to={'part_type__category': 'WING'}, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_as_wing', to='aircraft_production_app.part', verbose_name='Kanat (Parça SN)')),
                ('assembled_by_team', models.ForeignKey(limit_choices_to={'team_type': 'ASSEMBLY_TEAM'}, on_delete=django.db.models.deletion.PROTECT, to='aircraft_production_app.team', verbose_name='Montajı Yapan Takım')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_aircrafts_for_order', to='aircraft_production_app.workorder', verbose_name='İlgili İş Emri (Montaj)')),
            ],
            options={
                'verbose_name': 'Monte Edilmiş Hava Aracı',
                'verbose_name_plural': 'Monte Edilmiş Hava Araçları',
                'ordering': ['-assembly_date'],
            },
        ),
    ]
