# Generated by Django 5.2.1 on 2025-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_production_app', '0002_populate_fixed_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['-assembly_date'], 'verbose_name': 'Hazır Hava Aracı', 'verbose_name_plural': 'Hazır Hava Araçları'},
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Beklemede'), ('ASSIGNED', 'Atandı'), ('IN_PROGRESS', 'Üretimde'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20, verbose_name='Durum'),
        ),
    ]
