# Generated by Django 5.2.1 on 2025-05-10 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_production_app', '0004_aircraft_status_alter_aircraft_avionics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='assembled_by_personnel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled_aircrafts', to='aircraft_production_app.personnel', verbose_name='Montajı Yapan Personel'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='part',
            name='created_by_personnel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parts', to='aircraft_production_app.personnel', verbose_name='Üreten Personel'),
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Değiştirilme Tarihi'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='work_order',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status', 'CANCELLED'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_aircrafts_for_order', to='aircraft_production_app.workorder', verbose_name='İlgili İş Emri (Montaj)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='produced_by_team',
            field=models.ForeignKey(limit_choices_to=models.Q(('team_type', 'ASSEMBLY_TEAM'), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='produced_parts', to='aircraft_production_app.team', verbose_name='Üreten Takım'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
